### ISSUE TITLE
Need to update evSeq.yml dependencies

### ISSUE THREAD

**Issue by jlaw9** [fhalab/evSeq#39]
First of all, thanks for this tool! I just followed the recommended install instructions on the README and I'm getting the error below. It appears some of the dependencies have been updated recently. 

```
evSeq refseqs/DefaultRefSeq.csv ../data/multisite_runs
/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/bin/evSeq", line 33, in <module>
    sys.exit(load_entry_point('evSeq', 'console_scripts', 'evSeq')())
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/bin/evSeq", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jlaw/Dev/bpms/evSeq/evSeq/cmd.py", line 3, in <module>
    from evSeq.interfaces import execute_evseq
  File "/Users/jlaw/Dev/bpms/evSeq/evSeq/interfaces.py", line 20, in <module>
    from evSeq.run_evSeq import run_evSeq
  File "/Users/jlaw/Dev/bpms/evSeq/evSeq/run_evSeq.py", line 7, in <module>
    from .data_visualization import (generate_qualplot,
  File "/Users/jlaw/Dev/bpms/evSeq/evSeq/data_visualization.py", line 10, in <module>
    import holoviews as hv
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/holoviews/__init__.py", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/holoviews/annotators.py", line 10, in <module>
    from panel.pane import PaneBase
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/panel/__init__.py", line 1, in <module>
    from . import layout # noqa
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/panel/layout/__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/panel/layout/accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/panel/layout/base.py", line 11, in <module>
    from ..io.model import hold
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/panel/io/__init__.py", line 9, in <module>
    from ..config import config
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/panel/config.py", line 20, in <module>
    from .io.notebook import load_notebook
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/panel/io/notebook.py", line 39, in <module>
    from .resources import Bundle, Resources, _env, bundle_resources
  File "/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/panel/io/resources.py", line 23, in <module>
    from jinja2 import Environment, Markup, FileSystemLoader
ImportError: cannot import name 'Markup' from 'jinja2' (/Users/jlaw/Dev/miniforge3/envs/evSeq/lib/python3.8/site-packages/jinja2/__init__.py)
```

I found that if I update holoviews with `pip install --upgrade holoviews`, everything seems to work.

Output from pip:
```
$ pip install --upgrade holoviews
...
Installing collected packages: mdurl, xyzservices, uc-micro-py, markdown-it-py, Jinja2, mdit-py-plugins, linkify-it-py, bokeh, panel, holoviews
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 2.8
    Uninstalling Jinja2-2.8:
      Successfully uninstalled Jinja2-2.8
  Attempting uninstall: bokeh
    Found existing installation: bokeh 2.3.3
    Uninstalling bokeh-2.3.3:
      Successfully uninstalled bokeh-2.3.3
  Attempting uninstall: panel
    Found existing installation: panel 0.12.1
    Uninstalling panel-0.12.1:
      Successfully uninstalled panel-0.12.1
  Attempting uninstall: holoviews
    Found existing installation: holoviews 1.14.5
    Uninstalling holoviews-1.14.5:
      Successfully uninstalled holoviews-1.14.5
Successfully installed Jinja2-3.1.3 bokeh-3.1.1 holoviews-1.17.1 linkify-it-py-2.0.3 markdown-it-py-3.0.0 mdit-py-plugins-0.4.0 mdurl-0.1.2 panel-1.2.3 uc-micro-py-1.0.3 xyzservices-2024.4.0
```

**Comment by palmhjell** [comment]
Hi @jlaw9, thanks for the note! It looks like the `evSeq.yml` environment file lets some dependencies be unspecified, mainly `panel` here. (I think we expected `holoviews` to specify versions for its dependencies but I guess it doesn't.)

Your fix is good to know and thanks for figuring it out. We'd like to keep the `evSeq.yml` as close to the original release as possible so we know that everything behaves the same as when we released and validated evSeq. If you'd like to work with the release env, try making these two changes in your `evSeq.yml` file:

- Under the "Data visualization" section, add the line `- panel==0.12.1`.
- To get rid of the biopython warning at the beginning, change the `>=` specifier to `==` so it's held exactly at 1.78.

Let me know if this doesn't work for you!

**Comment by jlaw9** [comment]
Thanks @palmhjell, makes sense
